### ISSUE TITLE
询问anima-promise相关事宜

### ISSUE THREAD

**Issue by ishenli** [kaiailu/mixin#1]
你好，在spm上看了`anima-promise`的owner信息，想询问一下，这个模块是否还在继续维护，我现在开发`anima`的相关内容，所以为询问一下能否加我一下owner权限？

PS：因为找不到其他联系方式，所以在这个rep的提了这个问题~~

**Comment by kaiailu** [comment]
你的github账户给我 ， 我给你添加owner







--

祝您工作顺利
浙江大学 软件工程 韩凯



在 2015-10-18 21:31:45，"Michael Shen" <notifications@github.com> 写道：


你好，在spm上看了anima-promise的owner信息，想询问一下，这个模块是否还在继续维护，我现在开发anima的相关内容，所以为询问一下能否加我一下owner权限？

PS：因为找不到其他联系方式，所以在这个rep的提了这个问题~~

**Comment by kaiailu** [comment]
已经给你加了owner

**Comment by ishenli** [comment]
ok, 谢谢
